### ISSUE TITLE
find_near_matches() uses substitution for distance calculation even if max_substitutions=0 is set.

### ISSUE THREAD

**Issue by markussteindl** [taleinat/fuzzysearch#41] opened 2022-06-18 13:07 UTC
Reproduction:
```
find_near_matches('Hello world', 'Hello babab', max_substitutions=0, max_l_dist=5)
# [Match(start=0, end=11, dist=5, matched='Hello babab')]
```

Is this intended behavior?
Without substitution, the distance should be 10 and not 5.
Thus the above call should not return any matches.

**Comment by taleinat** [comment] 2022-07-14 18:39
Hey @Stonatus,

This is currently the intended behavior, yes. The "dist" attribute of matches describes the Levenstein / edit distance, which is indeed 5 in this case.

I can see that it could be useful to see the number of allowed changes needed given the input parameters. I'll leave this open while I consider if there's a neat way to implement this given the existing design.

**Comment by taleinat** [comment] 2024-06-24 19:00
I think this is too niche a use-case and not something that would be very simple to implement, so I'm going to close this request.

**Closed by taleinat** 2024-06-24 19:00 UTC
Labels: enhancement
